schema: 'schema/schema.graphql'
documents: 'src/**/*.graphql'
generates:
  src/gql/types.ts:
    plugins:
      - 'typescript'
  src/gql/apollo-helpers.ts:
    plugins:
      - typescript-apollo-client-helpers
  src/:
    preset: near-operation-file
    presetConfig:
      extension: .generated.ts
      baseTypesPath: src/gql/types.ts
    plugins:
      - typescript-operations
      - typescript-react-apollo
    config:
      withHooks: true
      namingConvention: 'keep'
      dedupeOperationSuffix: true
      omitOperationSuffix: true
