version: '3.6'
services:
  postgres:
    image: postgres:12
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: '${POSTGRES_USER:-postgres}'
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD:-postgres}'
      POSTGRES_DB: '${POSTGRES_DB:-meetup_db}'
  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    ports:
      - '8081:80'
    depends_on:
      - 'postgres'
    volumes:
      - ./pgadmin-data:/var/lib/pgadmin
      - ./servers.json:/pgadmin4/servers.json
      - ./pgpass:/pgpass
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
  server:
    build: ./server
    ports:
      - '4000:4000'
    depends_on:
      - 'postgres'
    volumes:
      - ./server/src:/app/src
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: '${POSTGRES_USER:-postgres}'
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD:-postgres}'
      POSTGRES_DB: '${POSTGRES_DB:-meetup_db}'
  client:
    build: ./client
    ports:
      - '3000:3000'
    depends_on:
      - 'server'
    volumes:
      - ./client/src:/app/src
      - ./client/schema:/app/schema
    environment:
      SERVER_HOST: server
      SERVER_PORT: 4000
